---
title: "Twitter Tibbles"
author: "Cassidy Bargell"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rtweet)
library(httpuv)
library(gtrendsR)
library(lubridate)
```

```{r twitter setup}

# Twitter set-up stuff

app_name <- "clb_twitter_app"
api_key <- "qFVEvxpEi0OmgWSmuIgG7RMPx"
api_secret_key <- "4KAvZL1OFZIITkrxY7xou9dAsTurvlvrXcd5edKX7NoVJ1sGyf"
token <- create_token(
  app = "clb_twitter_app",
  consumer_key = api_key,
  consumer_secret = api_secret_key)

path_to_token <- file.path(path.expand("~"), ".twitter_token.rds")
saveRDS(token, path_to_token)
env_var <- paste0("TWITTER_PAT=", path_to_token)
cat(env_var, file = file.path(path.expand("~"), ".Renviron"), 
  fill = TRUE, append = TRUE)

readRenviron("~/.Renviron")
```

```{r scrape twitter concussion}

# Can run all of the code below to scrape twitter for any given day

rugby_tweets <- search_tweets("rugby AND concussion", n = 1000, include_rts = FALSE) %>%
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

football_tweets <- search_tweets("football AND concussion", n = 1000, include_rts = FALSE) %>%
    select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

soccer_tweets <- search_tweets("soccer AND concussion", n = 1000, include_rts = FALSE) %>% 
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

hockey_tweets <- search_tweets("hockey AND concussion", n = 1000, include_rts = FALSE) %>% 
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)
```


```{r save RDS}

# Remeber to change the dates for all the below RDS documents 

file.create("rugby_3_20_20.RDS")
saveRDS(rugby_tweets, file = "rugby_3_20_20.RDS")

rugbytweets <- readRDS("rugby_3_20_20.RDS")

file.create("football_3_20_20.RDS")
saveRDS(football_tweets, file = "football_3_20_20.RDS")

footballtweets <- readRDS("football_3_20_20.RDS")

file.create("soccer_3_20_20.RDS")
saveRDS(soccer_tweets, file = "soccer_3_20_20.RDS")

soccertweets <- readRDS("soccer_3_20_20.RDS")

file.create("hockey_3_20_20.RDS")
saveRDS(hockey_tweets, file = "hockey_3_20_20.RDS")

hockeytweets <- readRDS("hockey_3_20_20.RDS")
```

```{r twitter CTE}

# CTE tweets

rugby_cte_tweets <- search_tweets("rugby AND CTE", n = 1000, include_rts = FALSE) %>%
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

football_cte_tweets <- search_tweets("football AND CTE", n = 1000, include_rts = FALSE) %>%
    select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

soccer_cte_tweets <- search_tweets("soccer AND CTE", n = 1000, include_rts = FALSE) %>% 
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

hockey_cte_tweets <- search_tweets("hockey AND CTE", n = 1000, include_rts = FALSE) %>% 
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)
```

```{r save CTE RDS}

# Save CTE twitter tibbles

file.create("rugbycte_3_20_20.RDS")
saveRDS(rugby_cte_tweets, file = "rugbycte_3_20_20.RDS")

rugbyctetweets <- readRDS("rugbycte_3_20_20.RDS")

file.create("footballcte_3_20_20.RDS")
saveRDS(football_cte_tweets, file = "footballcte_3_20_20.RDS")

footballctetweets <- readRDS("footballcte_3_20_20.RDS")

file.create("soccercte_3_20_20.RDS")
saveRDS(rugby_cte_tweets, file = "soccercte_3_20_20.RDS")

soccerctetweets <- readRDS("soccercte_3_20_20.RDS")

file.create("hockey_3_20_20.RDS")
saveRDS(hockey_cte_tweets, file = "hockeycte_3_20_20.RDS")

hockeyctetweets <- readRDS("hockeycte_3_20_20.RDS")
```

```{r}
rugby <- search_tweets("rugby", n = 1000, include_rts = FALSE) %>%
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

football <- search_tweets("football", n = 1000, include_rts = FALSE) %>%
    select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

soccer <- search_tweets("soccer", n = 1000, include_rts = FALSE) %>% 
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)

hockey <- search_tweets("hockey", n = 1000, include_rts = FALSE) %>% 
  select(user_id, 
         created_at, 
         screen_name, 
         text, 
         is_quote, 
         is_retweet, 
         retweet_count, 
         favorite_count, 
         quote_count, 
         reply_count, 
         hashtags)
```

```{r}
file.create("rugby_all_3_20_20.RDS")
saveRDS(rugby, file = "rugby_all_3_20_20.RDS")

file.create("football_all_3_20_20.RDS")
saveRDS(football, file = "football_all_3_20_20.RDS")

file.create("soccer_all_3_20_20.RDS")
saveRDS(soccer, file = "soccer_all_3_20_20.RDS")

file.create("hockey_all_3_20_20.RDS")
saveRDS(hockey, file = "hockey_all_3_20_20.RDS")

hockeytweets <- readRDS("hockey_all_3_20_20.RDS")
```


